apiVersion: v1
kind: Service
metadata:
  name: llamadoresdev-kustomize
  namespace: env-dev
  labels:
    service: llamadoresdev-kustomize
spec:
  type: ClusterIP
  selector:
    app: llamadoresdev-kustomize
  ports:
  - name: apache
    port: 80
    protocol: TCP
    targetPort: 80